# Site settings
title: CPDx - Ciclo de Palestras para Desenvolvedores
email: ufbacpdx@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  O Ciclo de Palestras para Desenvolvedores (CPDx) é uma iniciativa de funcionários da
  Superintendência de Tecnologia da Informação da UFBA (STI) para promover a discussão
  de tecnologias de desenvolvimento de software e tópicos relacionados.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://localhost:4000" # the base hostname & protocol for your site
twitter_username: ufbacpdx
github_username:  cpdx

# Build settings
markdown: kramdown
permalink: /:year/:month/:day/:title
